### ISSUE TITLE
Failing with the -n flag

### ISSUE THREAD

**Issue by seifreed** [karttoon/binsequencer#1]
Hi!

I'm trying to create a YARA rule for a nonpe file and binsequencer is crashing:

```
[+] Generating YARA rule for matches off of bytes from gold - malware/d41532ae67394c2f158f943fcf9651b2
Traceback (most recent call last):
  File "binsequencer.py", line 1864, in <module>
    main()
  File "binsequencer.py", line 1858, in main
    data = gen_yara(data["gold"], data, hashes, args)
  File "binsequencer.py", line 1210, in gen_yara
    data = gen_nonpeyara(data, hash, args, hashes)
  File "binsequencer.py", line 1195, in gen_nonpeyara
    data = yara_disa(data, args, hashes, code_section, virt_addr, rule)
  File "binsequencer.py", line 931, in yara_disa
    keep_bytes = ((4 - (op.prefix).count(0)) + (4 - (op.opcode).count(0))) * 2
  File "/binsequencer/lib/python3.6/site-packages/capstone/__init__.py", line 674, in __getattr__
    raise CsError(CS_ERR_SKIPDATA)
capstone.CsError: Information irrelevant for 'data' instruction in SKIPDATA mode (CS_ERR_SKIPDATA)
```

It seems an issue with capstone, but I don't know if it can be fixed from your side :-) !!!

**Comment by karttoon** [comment]
Looks like an issue with how Capstone handles the disassembly but since this is not actual assembly, we're the root problem. Crap in crap out as the saying goes :)

I pushed a new version (1.0.9) to the repo which will disable SKIPDATA if the nonpe flag is used. Tested on your XLS file above and appears to have resolved. Nice find!
