### ISSUE TITLE
SKIPDATA issue for PEFiles

### ISSUE THREAD

**Issue by seifreed** [karttoon/binsequencer#2]
Hi!

seems this issue is related with the previous one #1 

```
[+] Generating YARA rule for matches off of bytes from gold - malware/8db0d4d53c39a7d5d27617814c07693f311c500b9c791f55b2dc5d1ef5e3e570
Traceback (most recent call last):
  File "binsequencer.py", line 1867, in <module>
    main()
  File "binsequencer.py", line 1861, in main
    data = gen_yara(data["gold"], data, hashes, args)
  File "binsequencer.py", line 1208, in gen_yara
    data = gen_peyara(data, hash, args, hashes)
  File "binsequencer.py", line 1180, in gen_peyara
    data = yara_disa(data, args, hashes, code_section, virt_addr, rule)
  File "binsequencer.py", line 931, in yara_disa
    keep_bytes = ((4 - (op.prefix).count(0)) + (4 - (op.opcode).count(0))) * 2
  File "/usr/local/lib/python3.6/dist-packages/capstone/__init__.py", line 674, in __getattr__
    raise CsError(CS_ERR_SKIPDATA)
capstone.CsError: Information irrelevant for 'data' instruction in SKIPDATA mode (CS_ERR_SKIPDATA)
```

**Comment by seifreed** [comment]
Any update?

**Comment by karttoon** [comment]
Apologies, saw this when it came in and it fell off my radar. Pushed out a new update for 1.1.0 as I was able to replicate the issue with the sample from your post. Looks like there were bytes that don't disassemble which was screwing up a count I did - added a basic try/except around it to count them differently. Hope that helps
